### ISSUE TITLE
Unhandled exception. OpenQA.Selenium.DriverServiceNotFoundException: The file ./geckodriver does not exist.

### ISSUE THREAD

**Issue by JoseDeFreitas** [JoseDeFreitas/CodewarsLogger#1]
Awesome idea, but I couldn't make it work. When I run the "dotnet run" command in the terminal, I get this error:
**Unhandled exception. OpenQA.Selenium.DriverServiceNotFoundException: The file ./geckodriver does not exist.**
... Program.cs: line 50
Don't really know how to solve this issue. Would love to hear if you have any ideas!
If not, thanks anyway!

_Originally posted by @petermoyano in https://github.com/codewars/codewars.com/discussions/2496#discussioncomment-1426998_

**Comment by JoseDeFreitas** [comment]
Hello @petermoyano. Thank you for letting me know about this issue. As you see, I moved it in here because of the reasons I describe in [my reply to your comment](https://github.com/codewars/codewars.com/discussions/2496#discussioncomment-1427267) in the discussion.

The object created in the [line 50](https://github.com/JoseDeFreitas/CodewarsGitHubLogger/blob/35d163ec0be26d04831226e8651bd8eb0dd66119/CodewarsGitHubLogger/Program.cs#L50) of the program file (`new FirefoxDriver("./", options);`) takes two parameters: the path of the `geckodriver.exe` file and the `FirefoxOptions` object.

Make sure that the file `geckodriver.exe` is inside the `CodewarsGitHubLogger` folder (where `Program.cs` lies). If this is true, then you might solve the issue by changing the line 50 to this:

```cs
IWebDriver driver = new FirefoxDriver(options);
```

(As you see, you're not explicitly specifying the path of the driver, letting Selenium find it by itself).

You didn't provide any stack trace, so I don't really know what's causing this issue. I recommend you do that because I've already had this problem before, and removing the explicit reference to the path solved it. This is probably because of how each OS treats system paths.

If this doesn't work, please tell me, so I can investigate further. Also, send me the full error message (if any).

**Comment by JoseDeFreitas** [comment]
Two months have passed and there's no update on this issue. I'm writing this comment to let other users affected by this error know a possible way of solving this. If this is a general error I'll commit a change where the path string is set correctly.

**Comment by sashashi** [comment]
I'm getting the same error after fixing the directory of `geckodriver.exe` and line 50 of `Program.cs`:

```
Unhandled exception. OpenQA.Selenium.DriverServiceNotFoundException: The geckodriver file does not exist in the current directory or in a directory on the PATH environment variable. The driver can be downloaded at https://github.com/mozilla/geckodriver/releases.
   at OpenQA.Selenium.DriverService.FindDriverServiceExecutable(String executableName, Uri downloadUrl)
   at OpenQA.Selenium.Firefox.FirefoxDriverService.CreateDefaultService()
   at OpenQA.Selenium.Firefox.FirefoxDriver.CreateService(FirefoxOptions options)
   at OpenQA.Selenium.Firefox.FirefoxDriver..ctor(FirefoxOptions options)
   at CodewarsGitHubLogger.Program.Main(String[] args) in /Users/Sasha/CodewarsKatas/CodewarsGitHubLogger/Program.cs:line 50
   at CodewarsGitHubLogger.Program.<Main>(String[] args)
```

**Comment by sashashi** [comment]
The above error was fixed by adding the folder containing `geckodriver` to the PATH, the new error I'm getting is:
```Unhandled exception. System.InvalidOperationException: Expected browser binary location, but unable to find binary in default location, no 'moz:firefoxOptions.binary' capability provided, and no binary flag set on the command line (SessionNotCreated)
   at OpenQA.Selenium.WebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.WebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.WebDriver..ctor(ICommandExecutor executor, ICapabilities capabilities)
   at OpenQA.Selenium.Firefox.FirefoxDriver..ctor(FirefoxDriverService service, FirefoxOptions options, TimeSpan commandTimeout)
   at OpenQA.Selenium.Firefox.FirefoxDriver..ctor(FirefoxOptions options)
   at CodewarsGitHubLogger.Program.Main(String[] args) in /Users/Sasha/CodewarsKatas/CodewarsGitHubLogger/Program.cs:line 50
   at CodewarsGitHubLogger.Program.<Main>(String[] args)
```

**Comment by sashashi** [comment]
The above error was fixed by adding the folder containing `geckodriver` to the PATH, the new error I'm getting is:
```
Unhandled exception. System.InvalidOperationException: Expected browser binary location, but unable to find binary in default location, no 'moz:firefoxOptions.binary' capability provided, and no binary flag set on the command line (SessionNotCreated)
   at OpenQA.Selenium.WebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.WebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.WebDriver..ctor(ICommandExecutor executor, ICapabilities capabilities)
   at OpenQA.Selenium.Firefox.FirefoxDriver..ctor(FirefoxDriverService service, FirefoxOptions options, TimeSpan commandTimeout)
   at OpenQA.Selenium.Firefox.FirefoxDriver..ctor(FirefoxOptions options)
   at CodewarsGitHubLogger.Program.Main(String[] args) in /Users/Sasha/CodewarsKatas/CodewarsGitHubLogger/Program.cs:line 50
   at CodewarsGitHubLogger.Program.<Main>(String[] args)
```

**Comment by sashashi** [comment]
Lol haha I did not have Firefox, just installed. Still not getting it:
```
[GFX1-]: RenderCompositorSWGL failed mapping default framebuffer, no dt
console.warn: SearchSettings: "get: No settings file exists, new profile?" (new NotFoundError("Could not open the file at /var/folders/jf/5b57ph913bjg9j2sxhsjfsbm0000gn/T/rust_mozprofilezjX5E1/search.json.mozlz4", (void 0)))
console.error: BackgroundUpdate: 
  _reasonsToNotScheduleUpdates: Failed to check for Maintenance Service Registry Key: [Exception... "Component returned failure code: 0x80004001 (NS_ERROR_NOT_IMPLEMENTED) [nsIUpdateProcessor.getServiceRegKeyExists]"  nsresult: "0x80004001 (NS_ERROR_NOT_IMPLEMENTED)"  location: "JS frame :: resource://gre/modules/BackgroundUpdate.jsm :: _reasonsToNotScheduleUpdates :: line 241"  data: no]
1650408019102	Marionette	INFO	Listening on port 57605
Read port: 57605
console.warn: LoginRecipes: "getRecipes: falling back to a synchronous message for:" "https://www.codewars.com"
console.warn: LoginRecipes: "getRecipes: falling back to a synchronous message for:" "https://www.codewars.com"
console.warn: LoginRecipes: "getRecipes: falling back to a synchronous message for:" "https://www.codewars.com"
console.warn: LoginRecipes: "getRecipes: falling back to a synchronous message for:" "https://github.com"
console.warn: LoginRecipes: "getRecipes: falling back to a synchronous message for:" "https://github.com"
JavaScript error: resource://gre/modules/LoginManagerParent.jsm, line 136: TypeError: gRecipeManager is null
'Index' flag was not specified
1650408027214	Marionette	INFO	Stopped listening on port 57605

###!!! [Parent][PImageBridgeParent] Error: RunMessage(msgname=PImageBridge::Msg_WillClose) Channel closing: too late to send/recv, messages will be lost
```

**Comment by sashashi** [comment]
The above error can be fixed by adding the folder containing geckodriver to the PATH.

**Comment by JoseDeFreitas** [comment]
Hello, @sashashi. Thank you for providing the full error message. Did you fix the problem?

**Comment by sashashi** [comment]
> The above error can be fixed by adding the folder containing geckodriver to the PATH.

@JoseDeFreitas Yes, I think this issue can be closed now.

**Comment by JoseDeFreitas** [comment]
Okay, @sashashi. Thank you so much. I'm closing the issue.
